Blaze/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('intro.urls')),
    path('',include('accounts.urls')),
    path('',include('main.urls')),
    path('',include('mypageapp.urls',namespace='mypageapp'))
    ]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

demo/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('account.urls')),
    path('',include('main.urls')),
    ]

mypageapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *
from django.contrib.auth.views import LogoutView
from django.conf.urls.static import static
from django.conf import settings



app_name='mypage'
urlpatterns = [
    path('mypage',mypage,name="mypage"),
    path('mypageBlaze',mypageBlaze,name='mypageBlaze'),
    path('mypagePosts',mypagePosts,name='mypagePosts'),
    path('mypageComments',mypageComments,name='mypageComments'),
    path('go_editNickname',go_editNickname,name='go_editNickname'),
    path('editNickname', editNickname, name='editNickname'),
    path('signout',LogoutView.as_view(),name='signout'),

] +static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mypageapp/models.py
from django.db import models
from accounts.models import *
from main.models import *

mypageapp/forms.py
from django import forms
from django.db import models
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import check_password

class CheckPasswordForm(forms.Form):
    password = forms.CharField(label='password', widget=forms.PasswordInput(
        attrs={'class': 'form-control',}), 
    )
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = self.user.password
        
        if password:
            if not check_password(password, confirm_password):
                self.add_error('password', "The password doesn't match.")

mypageapp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.decorators import login_required
from .forms import CheckPasswordForm
from main.models import Post, Comment, Recomment
from accounts.models import BlazeUser

def mypage(request):
    user = request.user
    nickname = user.nickname
    email = user.email
    country = user.country
    return render(request,'mypage.html',{'nickname':nickname,'email':email,'country':country})

def mypageBlaze(request):
    user = request.user
    id = request.user.id
    email = request.user.email
    blazes = user.likes.all()
    # if user in like_users:
    return render(request,'mypageBlaze.html',{'blazes':blazes})

def mypagePosts(request):
    email = request.user.email
    id=request.user.id
    posts = Post.objects.all()
    post_list = posts.filter(author=id) # 내가 쓴글만
    # blog_list = Blog.objects.all().order_by('-id') # 블로그 객체 다 가져오기
    return render(request, 'mypagePosts.html', {'post_list':post_list})

def mypageComments(request):
    user = request.user
    id=request.user.id
    comments = Comment.objects.all()
    comment_list = comments.filter(user_id=id)
    recomments = Recomment.objects.all()
    recomment_list = recomments.filter(user_id=id)
    return render(request,'mypageComments.html', {'comment_list':comment_list,'recomment_list':recomment_list})

def go_editNickname(request):
    return render(request,'editNickname.html')

def editNickname(request):
    if request.method == "POST":
        user = request.user
        user.nickname = request.POST["nickname"]
        user.save()
        return redirect('mypageapp:mypage')
    return render(request,'mypage.html')

def signout(request):
    if request.method == "POST":
        pw_del = request.POST["pw_del"]
        user = request.user
        password = user.password
        if pw_del == password:
            user.delete()
            return redirect('main:main')
    return render(request, 'signout.html')

def profile_delete_view(request):
    if request.method == 'POST':
        password_form = CheckPasswordForm(request.user, request.POST)
        
        if password_form.is_valid():
            request.user.delete()
            logout(request)
            messages.success(request, "Sign Out has been completed.")
            return redirect('/intro/index/')
    else:
        password_form = CheckPasswordForm(request.user)

    return render(request, 'signout.html', {'password_form':password_form})

mypageapp/templates/baseForMypage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css"  href="{% static 'css/baseForMypage.css' %}">

    {% block head %} {% endblock %}
</head>
<body>
    <nav class="navMenu">
        <div class="main-logo"><a href='{% url "main" %}'><img src="{% static 'images/logo.png' %}" alt="logo-image" title="blaze!"/></a></div>
        <div class="nav-content">
            {% if user.is_authenticated %}
            <div class="nickname">HI {{ user.nickname }}!</div>
            <a class ="mypagetohome" href="{% url 'main' %}">HOME</a>
            {% else %}
            <button class="nav-login"> <a href="{% url 'signin' %}">login</a></button>
            {% endif %}


            <form method="POST" class="search-form" action="{% url 'search' %}">
                {%csrf_token%}
                <input type="search" placeholder="Title or Content" aria-label="Search" name="post" value="{{post}}"
                    id="search-input" id="search">
                <button type="submit" class="search-btn">Search</button>
            </form>

            <div class="create_write_btn">
                <a href="{%url 'create' %}">
                   
                    <img src="{% static 'images/create-btn.svg' %}" alt="create-btn" />
                </a>
            </div>


            <div class="alarm">
                <a href="">
                    <div class="alarm_btn">
                        <icon />
                    </div>
                </a>
            </div>
        </div>
    </nav>

    <div class="content-wrapper">
        <div class="category-wrapper">
            <div class="category-title">My Page</div>
                <div class="myaccount"><a href="{% url 'mypageapp:mypage' %}">My Account</a></div>
                <div class="posts"><a href="{% url 'mypageapp:mypagePosts' %}">Posts</a></div>
                <div class="comments"><a href="{% url 'mypageapp:mypageComments' %}">Comments</a></div>
                <div class="blaze"><a href="{% url 'mypageapp:mypageBlaze' %}">Blaze</a></div>
                <div class="signout">
                    <div class="btn-wrapper">
                        <button class="signOut-btn"><a href="{% url 'mypageapp:signout'%}">Sign Out</a></button>
                    </div>
                </div>
        </div>
        <div class="post-wrapper">
            {% block contents %}
            {% endblock %}
        </div>
    </div>
<script>

     // get flag emoji
     const getFlagEmoji = (countryCode) => countryCode.toUpperCase().replace(/./g,
            char => String.fromCodePoint(127397 + char.charCodeAt())
        );
        const flagReplace = document.querySelectorAll('[data-flag]');
        flagReplace.forEach(s => s.innerHTML = getFlagEmoji(s.dataset.flag))


</script>
{% block script %}

{% endblock %}
</body>
</html>

mypageapp/templates/editNickname.html
{% extends 'baseForMypage.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mypage.css' %}">
{% endblock %}

{% block contents %}

<div class="post-wrapper">
    <div class="post-container">
        <div class="post-menuname">
            Edit Nickname
        </div>
        <form action="{% url 'mypageapp:editNickname' %}" method="POST">
            {% csrf_token %}
            <div class="post-body">
                <div class="post-text">
                    <p>nickname = <input type="text" name="nickname" value="{{ user.nickname}}"></p>
                    <div class="nickbtn-wrapper">
                        <input class = "editNickname-btn" type="submit" value="confirm">
                        <!-- <button class="editNickname-btn"><a href="{% url 'mypageapp:go_editNickname'%}">Edit Nickname</a></button> -->
                    </div>
            
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

mypageapp/templates/mypage.html
{% extends 'baseForMypage.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mypage.css' %}">
{% endblock %}

{% block contents %}
<div class="post-container">
    <div class="post-nickname">
        <!-- <div class="nickname-flag">
            <p id="flag" data-flag="{{post.author.country}}"></p>
        </div> -->
        <!-- <div class="myaccounttop">My Account</div> -->
    </div>
    <div class="post-menuname">Nickname</div>
    <div class="post-body">
        <div class="post-text">
            <p>{{ nickname }}</p>
            <div class="nickbtn-wrapper">
                <button class="editNickname-btn"><a href="{% url 'mypageapp:go_editNickname'%}">Edit
                        Nickname</a></button>
            </div>
        </div>
    </div>
    <div class="post-menuname">E-Mail</div>
    <div class="post-body">
        <div class="post-text">
            <p>{{email}}</p>
        </div>
    </div>
    <div class="post-menuname">I'm from </div>
    <div class="post-body">
        <div class="post-text">
            <div class="flag-body">
                <p id="flag" data-flag="{{country}}"></p>
                <p>{{country}}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

mypageapp/templates/mypageBlaze.html
{% extends 'baseForMypage.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mypage.css' %}">
{% endblock %}

{% block contents %}
<div class="post-container">
    <div class="post-menuname">Blaze 🔥</div>
    <div class="post-body">
        {% for blaze in blazes %}
            <div class="post-text">
                <p>✔️<a href="{% url 'detail' blaze.id %}">{{ blaze.title }}</a></p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mypageapp/templates/mypageComments.html
{% extends 'baseForMypage.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mypage.css' %}">
{% endblock %}

{% block contents %}
<div class="post-container">
    <div class="post-menuname">
        My Comments
    </div>
    <div class="post-body">
        {% for comment in comment_list %}
        <div class="post-text">
            <a href="{% url 'detail' comment.post.id %}"><p>✔️{{ comment.content }}&nbsp;&nbsp;</a></p>
        </div>
    {% endfor %}
    </div>

    <div class="post-menuname">
        My Recomments
    </div>
    <div class="post-body">
        {% for recomment in recomment_list %}
            <div class="post-text">
                <a href="{% url 'detail' recomment.post.id %}"></a><p>✔️{{ recomment.content }}&nbsp;&nbsp;</a></p>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

mypageapp/templates/mypagePosts.html
{% extends 'baseForMypage.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mypage.css' %}">
{% endblock %}

{% block contents %}
<div class="post-container">
    <div class="post-menuname">
        My Posts
    </div>
    <div class="post-body">
        {% for post in post_list %}
            <div class="post-text"><p>✔️<a href="{% url 'detail' post.id %}">{{ post.title }}</a></p></div>
        {% endfor %}

    </div>
</div>
{% endblock %}